#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("cps");
entry("trace");
entry("sysinfo");
entry("setPriority");
entry("execve");
entry("getparentpid");
entry("print_pgtable");
entry("mmap");
entry("munmap");
entry("sh_var_read"); # 信号量：修改共享变量
entry("sh_var_write");#  信号量：修改共享变量
entry("sem_create"); # 信号量：
entry("sem_free");#  信号量：
entry("sem_p"); # 信号量：
entry("sem_v");#  信号量：
entry("symlink");
entry("mkf");
entry("shmgetat"); # 共享内存
entry("shmrefcount");#  共享内存
entry("sigalarm");
entry("sigreturn");
entry("connect");
entry("mqget");
entry("msgsnd");
entry("msgrcv");
entry("chmod");
entry("geti");
entry("recoveri");
entry("clone");
entry("join");
entry("rename");
entry("lseek");
entry("waitpid");
entry("getuid");
entry("setuid");
entry("reboot");
entry("readdir");
entry("access");
entry("umask");
entry("chown");
entry("flock");
entry("signal");
entry("pause");
entry("sigkill");
entry("send");
entry("recv");
entry("bind");
entry("listen");
entry("accept");
entry("socket");
entry("gettime");
entry("gethostname");
entry("sethostname");
entry("getenv");
entry("setenv");
entry("procinfo");
entry("kstat");
entry("truncate");
entry("dup2");
entry("getdents");
entry("nice");
entry("times");
entry("getppid");
entry("setpgid");
entry("getpgid");
entry("setsid");
entry("getsid");
entry("getgid");
entry("setgid");
entry("login");
entry("sudo");
entry("consctl");
entry("embassy_create_task");
entry("embassy_create_task_named");
entry("embassy_destroy_task");
entry("embassy_schedule");
entry("embassy_yield");
entry("embassy_delay_ms");
entry("embassy_wait_event");
entry("embassy_trigger_event");
entry("embassy_add_dependency");
entry("embassy_set_task_group");
entry("embassy_boost_priority");
entry("embassy_get_task_stats");
entry("embassy_get_global_stats");
entry("embassy_print_stats");
entry("qos_set");
entry("qos_get");
entry("qos_set_deadline");
entry("qos_stats");
entry("qos_print");
entry("sysfs_read");
entry("sysfs_list");
entry("slab_stats");
entry("hmdfs_register_device");
entry("hmdfs_device_offline");
entry("hmdfs_list_devices");
entry("hmdfs_share");
entry("hmdfs_unshare");
entry("hmdfs_list_shared");
entry("hmdfs_sync");
entry("hmdfs_stats");
entry("binder_register");
entry("binder_lookup");
entry("binder_release");
entry("binder_list");
entry("binder_stats");
entry("cgroup_create");
entry("cgroup_delete");
entry("cgroup_attach");
entry("cgroup_set_memory");
entry("cgroup_set_cpu");
entry("cgroup_list");
entry("cgroups_stats");
entry("ability_register");
entry("ability_start");
entry("ability_stop");
entry("ability_destroy");
entry("ability_back");
entry("ability_list");
entry("ability_stats");